services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    container_name: task-manager-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/tasksDB
      - JWT_SECRET=your-secret-key
    depends_on:
      - mongo
    env_file:
      - config.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  mongo-data: 